# Generated by Django 5.0.4 on 2024-05-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='order',
        ),
    ]
