# Generated by Django 5.0.3 on 2024-04-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('id', models.CharField(editable=True, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
